### ISSUE TITLE
Macros: A way to ignore a key + Always ignore computed variables

### ISSUE THREAD

**Issue by brzzdev** [nixzhu/Ananda#2]
I have a model:
```
@AnandaInit
public struct IDs: APICodable {
	public var id: Int { trakt }
	
	public let trakt: Int
	public let slug: String?
	public let tvdb: Int?
	public let imdb: String?
	public let tmdb: Int
}
```

The expanded macro is
```
public init(json: AnandaJSON) {
    self.id = json["id"].int()
    self.trakt = json["trakt"].int()
    self.slug = json["slug"].string
    self.tvdb = json["tvdb"].int
    self.imdb = json["imdb"].string
    self.tmdb = json["tmdb"].int()
}
```

with the self.id line giving me `Cannot assign to property: 'id' is a get-only property`

**Comment by nixzhu** [comment]
Thanks for your feedback! We need a better AnandaInit Macro. 😄

**Comment by nixzhu** [comment]
Try tag 0.3.1 https://github.com/nixzhu/Ananda/releases/tag/0.3.1

**Comment by brzzdev** [comment]
Looks good, thanks!

I'd love something like a `@AnandaIgnored` tag as well (consistent with Apple's `@ObservationIgnored` naming), as I have a `public var poster: URL?` value that I have to make a second data call to hydrate.

Then I think you'd have parity with what `Codable` and `CodingKeys` can do. Or at least the parts of it that I bump into 😅

**Comment by nixzhu** [comment]
OK, I will try to add a `@AnandaIgnored` macro later.
